apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaletestapp-hpa

spec:

  maxReplicas: 10
  minReplicas: 1

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaletestapp
  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 60